server:
  port: 8085
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/travel?serverTimezone=UTC&useSSL=false
    username: root
    password: 302680113
mybatis:
  type-aliases-package: com.travel.pojo
  configuration:
    map-underscore-to-camel-case: true